# Generated by Django 2.0.2 on 2018-02-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180224_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinorder',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
