# Generated by Django 2.0.2 on 2018-02-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_productinbasket'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinorder',
            name='session_key',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
