# Generated by Django 2.0.2 on 2018-02-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_productinorder_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinorder',
            name='session_key',
        ),
        migrations.AddField(
            model_name='productinbasket',
            name='session_key',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
