# Generated by Django 2.0.2 on 2018-02-27 10:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20180226_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinbasket',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productinbasket',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
