# Generated by Django 2.0.2 on 2018-02-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
