# Generated by Django 2.0.2 on 2018-03-22 19:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180322_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
